name_pools:
  family_names:
    - { en: Kim, ko: 김 }
    - { en: Lee, ko: 이 }
    - { en: Park, ko: 박 }
    - { en: Choi, ko: 최 }
    - { en: Jung, ko: 정 }
    - { en: Kang, ko: 강 }
    - { en: Cho, ko: 조 }
    - { en: Yoon, ko: 윤 }
    - { en: Jang, ko: 장 }
    - { en: Lim, ko: 임 }
  first_syllables:
    - { en: Min, ko: 민 }
    - { en: Seo, ko: 서 }
    - { en: Do, ko: 도 }
    - { en: Ji, ko: 지 }
    - { en: Hyun, ko: 현 }
    - { en: Tae, ko: 태 }
    - { en: Woo, ko: 우 }
    - { en: Jun, ko: 준 }
    - { en: Ye, ko: 예 }
    - { en: Gun, ko: 건 }
    - { en: Seung, ko: 승 }
    - { en: Dong, ko: 동 }
    - { en: Chang, ko: 창 }
    - { en: Jae, ko: 재 }
    - { en: Sung, ko: 성 }
    - { en: Kyung, ko: 경 }
    - { en: Byung, ko: 병 }
    - { en: Sang, ko: 상 }
    - { en: Yoon, ko: 윤 }
    - { en: Hye, ko: 혜 }
    - { en: Won, ko: 원 }
    - { en: Joo, ko: 주 }
    - { en: In, ko: 인 }
    - { en: Hoon, ko: 훈 }
    - { en: Young, ko: 영 }
    - { en: Se, ko: 세 }
  male_second_syllables:
    - { en: Jun, ko: 준 }
    - { en: Hyun, ko: 현 }
    - { en: Ho, ko: 호 }
    - { en: Woo, ko: 우 }
    - { en: Sung, ko: 성 }
    - { en: Hoon, ko: 훈 }
    - { en: Seo, ko: 서 }
    - { en: Jin, ko: 진 }
    - { en: Seok, ko: 석 }
    - { en: Min, ko: 민 }
    - { en: Yoon, ko: 윤 }
    - { en: Hyuk, ko: 혁 }
    - { en: Won, ko: 원 }
    - { en: Young, ko: 영 }
    - { en: Bin, ko: 빈 }
    - { en: Su, ko: 수 }
    - { en: Hwan, ko: 환 }
    - { en: Jae, ko: 재 }
    - { en: Gyum, ko: 겸 }
    - { en: Yul, ko: 율 }
    - { en: Chan, ko: 찬 }
    - { en: Beom, ko: 범 }
    - { en: Kyu, ko: 규 }
  female_second_syllables:
    - { en: Yeon, ko: 연 }
    - { en: Woo, ko: 우 }
    - { en: Seo, ko: 서 }
    - { en: Jin, ko: 진 }
    - { en: Ji, ko: 지 }
    - { en: Won, ko: 원 }
    - { en: Na, ko: 나 }
    - { en: Young, ko: 영 }
    - { en: Ra, ko: 라 }
    - { en: Ri, ko: 리 }
    - { en: Rin, ko: 린 }
    - { en: Kyung, ko: 경 }
    - { en: Ah, ko: 아 }
    - { en: Hyun, ko: 현 }
    - { en: Hee, ko: 희 }
    - { en: Suh, ko: 서 }
    - { en: Min, ko: 민 }
    - { en: Joo, ko: 주 }
    - { en: Yoon, ko: 윤 }
    - { en: Bin, ko: 빈 }
    - { en: Sol, ko: 솔 }
    - { en: Rae, ko: 래 }
    - { en: Ha, ko: 하 }
    - { en: Yu, ko: 유 }
  gender_neutral_second_syllables:
    - { en: Seo, ko: 서 }
    - { en: Jin, ko: 진 }
    - { en: Won, ko: 원 }
    - { en: Young, ko: 영 }
    - { en: Min, ko: 민 }
    - { en: Joo, ko: 주 }
    - { en: Yoon, ko: 윤 }
    - { en: Bin, ko: 빈 }
    - { en: Sol, ko: 솔 }
    - { en: Rae, ko: 래 }
    - { en: Ha, ko: 하 }
    - { en: Yu, ko: 유 }
    - { en: Hyun, ko: 현 }
    - { en: Woo, ko: 우 }
